service: predictor-grader

package:
  patterns:
    - '!src/**'
    - '!out-tsc/**'
    - '!scripts/**'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  check-matches:
    handler: dist/check-matches.handler
    events:
      - http:
          path: check-matches
          method: get
