service: predictor-grader

package:
  patterns:
    - '!src/**'
    - '!out-tsc/**'
    - '!scripts/**'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  check-matches:
    handler: dist/check-matches.handler
    timeout: 60
    events:
      - schedule: cron(* 9-23 * * ? *)
      # - http:
      #     path: check-matches
      #     method: get
